[package]
name = "matterweave-render"
version.workspace = true
edition = "2021"
rust-version = "1.96"
publish = false

[dependencies]
matterweave-core = { path = "../matterweave-core" }
ash = "=0.38.0"
ash-window = "=0.13.0"
raw-window-handle = "=0.6.2"
winit = { version = "=0.30.12", features = ["android-native-activity"] }
bytemuck = { version = "=1.23.2", features = ["derive"] }
font8x8 = "=0.3.1"
glam = "=0.30.9"

[build-dependencies]
naga = { version = "=24.0.0", features = ["wgsl-in", "spv-out"] }
